### ISSUE TITLE
[Feat] 응원 한 마디 - UserDefaults 설정

### ISSUE THREAD

**Issue by Taerogrammer** [DeveloperAcademy-POSTECH/MC2-morning-Team12-DreamLog#116]
## 이슈
- 응원 한 마디 기능은 UserDefaults로 적용하는 것이 효율적일 것 같아서 그것으로 할 예정입니다.

## To - Do
- UserDefaults 설정하기

**Comment by dayjack** [comment]
제가 응원기능을 그냥 디비방식으로 바꿔놓아서 처리되었습니다
